DemoGitHub/Models/Aluno.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DemoGitHub.Models
{
    public class Aluno
    {
        public int AlunoId { get; set; }
        [Required]
        public string Nome { get; set; }
        public string Campus { get; set; }
        public string Curso { get; set; }
        public string Sexo { get; set; }
    }
}

DemoGitHub/Models/ErrorViewModel.cs
using System;

namespace DemoGitHub.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DemoGitHub/ViewModels/AlunoViewModel.cs
using DemoGitHub.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DemoGitHub.ViewModels
{
    public class AlunoViewModel
    {
        public int AlunoId { get; set; }
        [Required]
        public string Nome { get; set; }
        public string Campus { get; set; }
        public string Curso { get; set; }
        public string Sexo { get; set; }
        public DateTime Aniversario { get; set; }

        public Aluno aluno { get; set; }

    }
}

DemoGitHub/Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DemoGitHub.Models;
using Microsoft.AspNetCore.Http;
using DemoGitHub.Repository;
using DemoGitHub.ViewModels;

namespace DemoGitHub.Controllers
{
    public class AlunosController : Controller
    {

        #region Ações do Controlador

        #region Method Index -> GetAllAlunos - OK
        public ActionResult Index()
        {
            //var alunoRepository = new AlunoRepository();
            //var alunos = new List<AlunoViewModel>();

            IEnumerable<Aluno> alunos = AlunoRepository.GetalunoList();

            IEnumerable<AlunoViewModel> alunosviewmodel = alunos.Select(x => new AlunoViewModel
            {
                AlunoId = x.AlunoId,
                Nome = x.Nome,
                Campus = x.Campus,
                Curso = x.Curso,
                Sexo =  x.Sexo,
                Aniversario = x.Aniversario
            });
            return View(alunosviewmodel);
        }
        #endregion

        #region Methods Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Aluno aluno) // Recolher dados do formulario
        {

            AlunoRepository.Create(aluno);

            return RedirectToAction("Index");
        }
        #endregion

        #region Methods Edit
        public ActionResult Edit(int id)
        {
            Aluno aluno = AlunoRepository.BuscarId(id);
            AlunoViewModel alunoviewmodel = new AlunoViewModel
            {
                Nome = aluno.Nome,
                Campus = aluno.Campus,
                Curso = aluno.Curso,
                Sexo = aluno.Sexo,
                Aniversario = aluno.Aniversario
            };
            return View(alunoviewmodel);
        }



        [HttpPost]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                Aluno aluno = new Aluno();
                aluno.Nome = collection["Nome"];
                aluno.Campus = collection["Campus"];
                aluno.Curso = collection["Curso"];
                aluno.Sexo = collection["Sexo"];
                aluno.Aniversario = DateTime.Parse(collection["Aniversario"]);
                //aluno.Aniversario = Convert.ToDateTime(collection["Aniversario"]);


                AlunoRepository.EditAluno(id, aluno);
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region Methods Delete
        public ActionResult Delete(int id)
        {
            Aluno aluno = AlunoRepository.BuscarId(id);
            AlunoViewModel alunoviewmodel = new AlunoViewModel
            {
                AlunoId = aluno.AlunoId,
                Nome = aluno.Nome,
                Campus = aluno.Campus,
                Curso = aluno.Curso,
                Sexo = aluno.Sexo,
                Aniversario = aluno.Aniversario

            };
            return View(alunoviewmodel);
        }

        [HttpPost]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                AlunoRepository.DeleteAluno(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region Method Details
        public ActionResult Details(int id)
        {
            Aluno aluno = AlunoRepository.BuscarId(id);
            AlunoViewModel alunoviewmodel = new AlunoViewModel
            {
                AlunoId = aluno.AlunoId,
                Nome = aluno.Nome,
                Campus = aluno.Campus,
                Curso = aluno.Curso,
                Sexo = aluno.Sexo,
                Aniversario = aluno.Aniversario

            };
            return View(alunoviewmodel);
        }
        #endregion

        #region Methods Buscar
        public ActionResult Buscar(string pesquisa)
        {
            IEnumerable<Aluno> alunos = AlunoRepository.BuscarAluno(pesquisa);

            IEnumerable<AlunoViewModel> alunosviewmodel = alunos.Select(x => new AlunoViewModel
            {
                AlunoId = x.AlunoId,
                Nome = x.Nome,
                Campus = x.Campus,
                Curso = x.Curso,
                Sexo = x.Sexo,
                Aniversario = x.Aniversario
            });
            return View(alunosviewmodel);
        }

        //[HttpPost]
        //public ActionResult Buscar(string pesquisa)
        //{
        //    try
        //    {
        //        return View(BuscarAluno(pesquisa));
        //    }
        //    catch
        //    {
        //        return View();

        //    }
        //}
        #endregion

        #endregion
    }
}

DemoGitHub/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DemoGitHub.Models;

namespace DemoGitHub.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            


            return View();
        }

       

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DemoGitHub/Views/Alunos/Buscar.cshtml
@model IEnumerable<DemoGitHub.ViewModels.AlunoViewModel>

@{
    ViewData["Title"] = "Buscar";
}

<h1>Buscar</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AlunoId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Campus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Curso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AlunoId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Campus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Curso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

DemoGitHub/Views/Alunos/Create.cshtml
@model DemoGitHub.ViewModels.AlunoViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Campus" class="control-label"></label>
                <input asp-for="Campus" class="form-control" />
                <span asp-validation-for="Campus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Curso" class="control-label"></label>
                <input asp-for="Curso" class="form-control" />
                <span asp-validation-for="Curso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aniversario" class="control-label"></label>
                <input asp-for="Aniversario" class="form-control" />
                <span asp-validation-for="Aniversario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoGitHub/Views/Alunos/Delete.cshtml
@model DemoGitHub.ViewModels.AlunoViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AlunoId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AlunoId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Campus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Campus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Curso)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Curso)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Aniversario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Aniversario)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DemoGitHub/Views/Alunos/Details.cshtml
@model DemoGitHub.ViewModels.AlunoViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AlunoId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AlunoId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Campus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Campus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Curso)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Curso)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Aniversario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Aniversario)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AlunoId }) |
    <a asp-action="Index">Back to List</a>
</div>

DemoGitHub/Views/Alunos/Edit.cshtml
@model DemoGitHub.ViewModels.AlunoViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Campus" class="control-label"></label>
                <input asp-for="Campus" class="form-control" />
                <span asp-validation-for="Campus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Curso" class="control-label"></label>
                <input asp-for="Curso" class="form-control" />
                <span asp-validation-for="Curso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aniversario" class="control-label"></label>
                <input asp-for="Aniversario" class="form-control" />
                <span asp-validation-for="Aniversario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoGitHub/Views/Alunos/Index.cshtml
@model IEnumerable<DemoGitHub.ViewModels.AlunoViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form asp-controller="Alunos" asp-action="Buscar">
    <p>
        Title: <input type="text" name="pesquisa">
        <input type="submit" value="Pesquisa" />
    </p>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AlunoId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Campus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Curso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aniversario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AlunoId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Campus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Curso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aniversario)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.AlunoId }) |
                @Html.ActionLink("Details", "Details", new { id = item.AlunoId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.AlunoId })
            </td>
        </tr>
}
    </tbody>
</table>

DemoGitHub/Views/Alunos/IndexAluno.cshtml
@model IEnumerable<DemoGitHub.ViewModels.AlunoViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h2>Buscar</h2>
<span>Digite o nome ou parte do nome do aluno</span>
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <div class="form-group">
        <div class="col-md-10">
            <input type="text" name="pesquisa" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Buscar" class="btn btn-default" />
        </div>
    </div>

</div>

}

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AlunoId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Campus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Curso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AlunoId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Campus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Curso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.AlunoId }) |
                @Html.ActionLink("Details", "Details", new { id = item.AlunoId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.AlunoId })
            </td>
        </tr>
}
    </tbody>
</table>

DemoGitHub/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DemoGitHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoGitHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoGitHub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DemoGitHub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>